
@api = http://localhost:3000/normas
@apii = http://localhost:3000/search

### Get all normas
GET {{api}}


### Add new norma
POST {{api}}
Content-Type: application/json

{
    "id" : 100049,
    "numero_norma": "10011",
    "tipo_norma": 2,
    "tema": "prueba 1",
    "actor": "1,2,3",
    "fecIni" : "24/12/2022",
    "fecFin": ""
}


### get specific norma
GET {{api}}/100049


### update validity norma by id
PUT {{api}}/100049
Content-Type: application/json

{
    "fecFin": "01/01/2025"
}


### get norma by name
POST {{apii}}
Content-Type: application/json

{
     "name": "%docente%"
}
