
@api = http://localhost:3000/normas
@apii = http://localhost:3000/search

### Get all normas
GET {{api}}


### Add new norma
POST {{api}}
Content-Type: application/json

{
    "id" : 100059,
    "numero_norma": "10011",
    "tipo_norma": 2,
    "tema": "prueba 50",
    "actor": "1 2 3",
    "fecIni" : "24/12/2022",
    "fecFin": ""
}


### get specific norma
GET {{api}}/100059


### update validity norma by id
PUT {{api}}/100059
Content-Type: application/json

{
    "tema" : "esto no es una prueba",
    "fecFin": "01/01/2026"
    
}


### get norma by name
POST {{apii}}
Content-Type: application/json

{
     "name": "%%"
}
